# This role changes the hostname

- name: set the hostname
  hostname: 
    name: "{{hostname}}"
  become: yes

- name: add host to hosts file
  lineinfile: 
    path: /etc/hosts
    line: '127.0.0.1 {{ hostname }}'
  become: yes