# This role installs Metricbeat

# Install Metricbeat 
- name: Install Metricbeat 
  apt:
   name: metricbeat
   update_cache: yes
    
# Start Metricbeat
- name: Start Metricbeat
  service:
   name: metricbeat
   state: started