# This playbook performs post provisioning config of ubuntu
- name: ubuntu config
  hosts: ubuntu
  tasks:
    - name: create the .ssh dir if it is not there
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700
    - name: create authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: 0644
    - name: copy over key block and append to auth keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"

    - name: create sudoers dropin for 480
      file:
        path: /etc/sudoers.d/480
        state: touch
        mode: 0440
      become: yes

    - name: create a drop in entry in /etc/sudoers.d/480
      blockinfile:
        dest: /etc/sudoers.d/480
        block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL" 
      become: yes

    - name: set the hostname
      hostname: 
        name: "{{hostname}}"
      become: yes

    - name: add host to hosts file
      lineinfile: 
        path: /etc/hosts
        line: '127.0.0.1 {{ hostname }}'
      become: yes

    - name: Generate netplan config 
      template:
        src: files/ubuntu/networking.j2
        dest: /etc/netplan/00-installer-config.yaml
      become: yes

    - name: bounce the box
      shell: "sudo netplan apply && sleep 5 && shutdown -r"
      become: yes
      async: 1
      poll: 0