- name: Install and configure Filebeat
  hosts: siemagents
  become: true
  become_user: root
  tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Install Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
        state: present

    - name: Install Filebeat
      apt:
        name: filebeat
        state: present

    - name: Configure Filebeat
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: "0640"
      notify:
        - restart filebeat

  handlers:
    - name: restart filebeat
      service:
        name: filebeat
        state: restarted
